package com.composum.ai.composum.bundle;

import java.io.InputStream;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * Writes the prompts defined in /create/predefinedprompts.json as Sling resources in AEM format,
 * see e.g. aem/ui.content/src/main/content/jcr_root/conf/composum-ai/settings/dialogs/contentcreation/predefinedprompts/.content.xml
 */
public class WritePredefinedPromptsInAEMFormat {

    public static void main(String[] args) {
        final String jsonfile = "/create/predefinedprompts.json";
        jsonListToXML(WritePredefinedPromptsInAEMFormat.class, jsonfile, false);
    }

    static void jsonListToXML(Class<?> mainClass, String jsonfile, boolean swapped) {
        Gson gson = new GsonBuilder().disableHtmlEscaping().create();
        InputStream in = WritePredefinedPromptsInAEMFormat.class.getResourceAsStream(jsonfile);
        Map<String, String> json = gson.fromJson(new java.io.InputStreamReader(in), Map.class);
        System.out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        System.out.println("<!-- generated by " + mainClass.getName() + " - can be used for updating, too. -->");
        System.out.println("<jcr:root xmlns:sling=\"http://sling.apache.org/jcr/sling/1.0\" xmlns:jcr=\"http://www.jcp.org/jcr/1.0\" xmlns:nt=\"http://www.jcp.org/jcr/nt/1.0\" jcr:primaryType=\"sling:OrderedFolder\">");
        for (Map.Entry<String, String> entry : json.entrySet()) {
            String nodename = entry.getKey().toLowerCase().trim().replaceAll("[^a-z]", "_");
            nodename = StringUtils.defaultIfBlank(nodename, "empty");
            // use a xml attribute encoder
            String value = entry.getValue().replaceAll("&", "&amp;").replaceAll("\"", "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
            String text = entry.getKey().replaceAll("&", "&amp;").replaceAll("\"", "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
            if (swapped) {
                String help = value;
                value = text;
                text = help;
            }
            value = StringUtils.defaultIfBlank(value, "-");
            text = StringUtils.defaultIfBlank(text, "-");
            System.out.println("    <" + nodename + " jcr:primaryType=\"nt:unstructured\" sling:resourceType=\"nt:unstructured\" " +
                    "\n        text=\"" + text + "\"" +
                    "\n        value=\"" + value + "\"></" + nodename + ">");
        }
        System.out.println("</jcr:root>");
    }
}
